### ISSUE TITLE
開発に関するすべてのisuue追加＆更新

### ISSUE THREAD

**Issue by kos0514** [kos0514/wicum#32]
# 【機能要件】
・開発に関するすべてのisuue追加＆更新

# 【タスク】
- [x] isuue洗い出し。
- [x] isuue内のタスクの洗い出し。
- [x] マイルストーンを設定する。

# 【調査事項】

**Comment by heqg** [comment]
すべてのタスク洗い出し。
 マイルストーンを設定する。

**Comment by kos0514** [comment]
とりあえず洗い出し、マイルストーン設定は完了。
今後は都度修正や追加を行います。
